In [2]:
import pandas as pd
import numpy as np
from xgboost import XGBRegressor
import joblib

In [4]:
# 1. Define schema & load training data
index_cols = ['unit_nr', 'time_cycles']
setting_cols = ['setting_1', 'setting_2', 'setting_3']
sensor_cols = [f's_{i}' for i in range(1, 22)]
col_names = index_cols + setting_cols + sensor_cols

In [5]:
df = pd.read_csv('data/train_FD001.txt', sep=r'\s+', header=None, names=col_names)

In [16]:
# 2. Calculate target RUL per engine
max_cycles = df.groupby('unit_nr')['time_cycles'].transform('max')
df['RUL'] = (max_cycles - df['time_cycles']).clip(upper=125)

In [11]:
pd.set_option('display.max_columns', None)

In [13]:
df.head(20)

,unit_nr,time_cycles,setting_1,setting_2,setting_3,s_1,s_2,s_3,s_4,s_5,s_6,s_7,s_8,s_9,s_10,s_11,s_12,s_13,s_14,s_15,s_16,s_17,s_18,s_19,s_20,s_21,RUL
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,21.61,554.36,2388.06,9046.19,1.3,47.47,521.66,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190,125
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,21.61,553.75,2388.04,9044.07,1.3,47.49,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236,125
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,21.61,554.26,2388.08,9052.94,1.3,47.27,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442,125
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,21.61,554.45,2388.11,9049.48,1.3,47.13,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739,125
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,21.61,554.00,2388.06,9055.15,1.3,47.28,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044,125
5,1,6,-0.0043,-0.0001,100.0,518.67,642.10,1584.47,1398.37,14.62,21.61,554.67,2388.02,9049.68,1.3,47.16,521.68,2388.03,8132.85,8.4108,0.03,391,2388,100.0,38.98,23.3669,125
6,1,7,0.0010,0.0001,100.0,518.67,642.48,1592.32,1397.77,14.62,21.61,554.34,2388.02,9059.13,1.3,47.36,522.32,2388.03,8132.32,8.3974,0.03,392,2388,100.0,39.10,23.3774,125
7,1,8,-0.0034,0.0003,100.0,518.67,642.56,1582.96,1400.97,14.62,21.61,553.85,2388.00,9040.80,1.3,47.24,522.47,2388.03,8131.07,8.4076,0.03,391,2388,100.0,38.97,23.3106,125
8,1,9,0.0008,0.0001,100.0,518.67,642.12,1590.98,1394.80,14.62,21.61,553.69,2388.05,9046.46,1.3,47.29,521.79,2388.05,8125.69,8.3728,0.03,392,2388,100.0,39.05,23.4066,125
9,1,10,-0.0033,0.0001,100.0,518.67,641.71,1591.24,1400.46,14.62,21.61,553.59,2388.05,9051.70,1.3,47.03,521.79,2388.06,8129.38,8.4286,0.03,393,2388,100.0,38.95,23.4694,125
10,1,11,0.0018,-0.0003,100.0,518.67,642.28,1581.75,1400.64,14.62,21.61,554.54,2388.05,9049.61,1.3,47.15,521.40,2388.01,8140.58,8.4340,0.03,392,2388,100.0,38.94,23.4787,125
11,1,12,0.0016,0.0002,100.0,518.67,642.06,1583.41,1400.15,14.62,21.61,554.52,2388.09,9049.37,1.3,47.18,521.80,2388.02,8134.25,8.3938,0.03,391,2388,100.0,39.06,23.3660,125
12,1,13,-0.0019,0.0004,100.0,518.67,643.07,1582.19,1400.83,14.62,21.61,553.44,2388.12,9046.82,1.3,47.38,521.85,2388.08,8128.10,8.4152,0.03,393,2388,100.0,38.93,23.2757,125
13,1,14,0.0009,-0.0000,100.0,518.67,642.35,1592.95,1399.16,14.62,21.61,554.48,2388.09,9047.37,1.3,47.44,521.67,2388.00,8134.43,8.3964,0.03,393,2388,100.0,39.18,23.3826,125
14,1,15,-0.0018,-0.0003,100.0,518.67,642.43,1583.82,1402.13,14.62,21.61,553.64,2388.11,9052.22,1.3,47.30,522.50,2388.08,8127.56,8.4199,0.03,391,2388,100.0,38.99,23.3500,125
15,1,16,0.0006,0.0005,100.0,518.67,642.13,1587.98,1404.50,14.62,21.61,553.94,2388.05,9049.34,1.3,47.24,521.49,2388.07,8136.11,8.3936,0.03,392,2388,100.0,38.97,23.4550,125
16,1,17,0.0002,0.0002,100.0,518.67,642.58,1584.96,1399.95,14.62,21.61,553.80,2388.06,9054.92,1.3,47.12,521.89,2388.04,8137.27,8.4542,0.03,392,2388,100.0,38.81,23.3319,125
17,1,18,-0.0031,-0.0001,100.0,518.67,642.62,1591.04,1396.12,14.62,21.61,554.20,2388.05,9049.55,1.3,47.21,521.76,2388.07,8132.73,8.4028,0.03,392,2388,100.0,38.89,23.3987,125
18,1,19,0.0032,-0.0003,100.0,518.67,641.79,1587.56,1400.35,14.62,21.61,554.18,2388.04,9053.99,1.3,47.40,521.89,2388.03,8129.13,8.4321,0.03,391,2388,100.0,38.80,23.3464,125
19,1,20,-0.0037,0.0001,100.0,518.67,643.04,1581.11,1405.23,14.62,21.61,554.81,2388.05,9045.90,1.3,47.22,522.07,2388.02,8129.71,8.4210,0.03,392,2388,100.0,39.03,23.4220,125

In [14]:
df.tail(20)

,unit_nr,time_cycles,setting_1,setting_2,setting_3,s_1,s_2,s_3,s_4,s_5,s_6,s_7,s_8,s_9,s_10,s_11,s_12,s_13,s_14,s_15,s_16,s_17,s_18,s_19,s_20,s_21,RUL
20611,100,181,0.0024,-0.0005,100.0,518.67,643.25,1597.83,1414.63,14.62,21.61,552.24,2388.18,9065.34,1.3,47.99,520.42,2388.22,8139.30,8.5518,0.03,396,2388,100.0,38.52,23.1774,19
20612,100,182,0.0007,-0.0001,100.0,518.67,643.52,1604.31,1417.73,14.62,21.61,551.47,2388.19,9063.62,1.3,47.75,520.05,2388.22,8140.87,8.4855,0.03,396,2388,100.0,38.41,23.1289,18
20613,100,183,-0.0011,-0.0002,100.0,518.67,643.34,1594.60,1427.27,14.62,21.61,551.83,2388.20,9066.08,1.3,48.00,520.64,2388.23,8144.21,8.5006,0.03,395,2388,100.0,38.49,23.0709,17
20614,100,184,0.0027,-0.0004,100.0,518.67,642.91,1598.88,1420.89,14.62,21.61,551.72,2388.25,9064.14,1.3,47.98,520.05,2388.20,8142.28,8.4989,0.03,396,2388,100.0,38.44,23.1229,16
20615,100,185,-0.0014,0.0004,100.0,518.67,643.95,1600.81,1420.34,14.62,21.61,551.92,2388.19,9069.95,1.3,47.75,520.71,2388.20,8142.32,8.4804,0.03,395,2388,100.0,38.60,23.2127,15
20616,100,186,0.0026,0.0004,100.0,518.67,643.61,1593.55,1425.32,14.62,21.61,552.28,2388.20,9066.46,1.3,48.06,520.66,2388.27,8138.08,8.4735,0.03,394,2388,100.0,38.51,23.1173,14
20617,100,187,0.0015,0.0002,100.0,518.67,643.63,1596.96,1421.49,14.62,21.61,551.53,2388.22,9065.94,1.3,48.04,520.15,2388.22,8140.49,8.5087,0.03,396,2388,100.0,38.67,23.2308,13
20618,100,188,-0.0008,-0.0002,100.0,518.67,643.19,1597.77,1426.57,14.62,21.61,550.77,2388.26,9067.68,1.3,48.29,519.98,2388.21,8139.94,8.4814,0.03,395,2388,100.0,38.36,23.0552,12
20619,100,189,0.0015,0.0001,100.0,518.67,643.69,1599.85,1423.15,14.62,21.61,551.61,2388.18,9069.69,1.3,47.99,519.50,2388.24,8139.78,8.4870,0.03,397,2388,100.0,38.65,23.0591,11
20620,100,190,-0.0001,0.0002,100.0,518.67,643.12,1594.45,1426.04,14.62,21.61,551.06,2388.21,9064.74,1.3,47.99,519.52,2388.26,8142.28,8.5162,0.03,395,2388,100.0,38.42,23.0603,10
20621,100,191,-0.0005,-0.0000,100.0,518.67,643.69,1610.87,1427.19,14.62,21.61,551.78,2388.26,9068.90,1.3,48.07,519.80,2388.28,8143.56,8.5092,0.03,398,2388,100.0,38.39,23.1218,9
20622,100,192,-0.0009,0.0001,100.0,518.67,643.53,1601.23,1419.48,14.62,21.61,551.14,2388.17,9060.45,1.3,48.18,520.59,2388.21,8143.46,8.4892,0.03,397,2388,100.0,38.56,23.0770,8
20623,100,193,-0.0001,0.0002,100.0,518.67,643.09,1599.81,1428.93,14.62,21.61,552.04,2388.29,9067.57,1.3,48.19,520.11,2388.19,8142.02,8.5424,0.03,397,2388,100.0,38.47,23.0230,7
20624,100,194,-0.0011,0.0003,100.0,518.67,643.72,1597.29,1427.41,14.62,21.61,551.99,2388.23,9068.85,1.3,48.12,519.55,2388.22,8139.67,8.5215,0.03,394,2388,100.0,38.38,23.1324,6
20625,100,195,-0.0002,-0.0001,100.0,518.67,643.41,1600.04,1431.90,14.62,21.61,551.42,2388.23,9069.69,1.3,48.22,519.71,2388.28,8142.90,8.5519,0.03,394,2388,100.0,38.14,23.1923,5
20626,100,196,-0.0004,-0.0003,100.0,518.67,643.49,1597.98,1428.63,14.62,21.61,551.43,2388.19,9065.52,1.3,48.07,519.49,2388.26,8137.60,8.4956,0.03,397,2388,100.0,38.49,22.9735,4
20627,100,197,-0.0016,-0.0005,100.0,518.67,643.54,1604.50,1433.58,14.62,21.61,550.86,2388.23,9065.11,1.3,48.04,519.68,2388.22,8136.50,8.5139,0.03,395,2388,100.0,38.30,23.1594,3
20628,100,198,0.0004,0.0000,100.0,518.67,643.42,1602.46,1428.18,14.62,21.61,550.94,2388.24,9065.90,1.3,48.09,520.01,2388.24,8141.05,8.5646,0.03,398,2388,100.0,38.44,22.9333,2
20629,100,199,-0.0011,0.0003,100.0,518.67,643.23,1605.26,1426.53,14.62,21.61,550.68,2388.25,9073.72,1.3,48.39,519.67,2388.23,8139.29,8.5389,0.03,395,2388,100.0,38.29,23.0640,1
20630,100,200,-0.0032,-0.0005,100.0,518.67,643.85,1600.38,1432.14,14.62,21.61,550.79,2388.26,9061.48,1.3,48.20,519.30,2388.26,8137.33,8.5036,0.03,396,2388,100.0,38.37,23.0522,0

In [15]:
same_values = df.columns[df.iloc[0] == df.iloc[-1]]
print(df[same_values].iloc[[0, -1]])

       setting_3     s_1    s_5    s_6  s_10  s_16  s_18   s_19
0          100.0  518.67  14.62  21.61   1.3  0.03  2388  100.0
20630      100.0  518.67  14.62  21.61   1.3  0.03  2388  100.0

The sensor data columns above are uninformative because they are constant and don't change. Therefore, we will drop them.

In [17]:
# 3. Drop uninformative constant sensors
drop_cols = ['s_1', 's_5', 's_6', 's_10', 's_16', 's_18', 's_19']
features = [col for col in setting_cols + sensor_cols if col not in drop_cols]

In [18]:
# 4. Train XGBoost model
X, y = df[features], df['RUL']
model = XGBRegressor(n_estimators=100, learning_rate=0.05, max_depth=5, random_state=42)
model.fit(X, y)

XGBRegressor(base_score=None, booster=None, callbacks=None,
             colsample_bylevel=None, colsample_bynode=None,
             colsample_bytree=None, device=None, early_stopping_rounds=None,
             enable_categorical=False, eval_metric=None, feature_types=None,
             feature_weights=None, gamma=None, grow_policy=None,
             importance_type=None, interaction_constraints=None,
             learning_rate=0.05, max_bin=None, max_cat_threshold=None,
             max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
             max_leaves=None, min_child_weight=None, missing=nan,
             monotone_constraints=None, multi_strategy=None, n_estimators=100,
             n_jobs=None, num_parallel_tree=None, ...)

In [19]:
# 5. Save model and list of features
joblib.dump(model, 'model.pkl')
joblib.dump(features, 'features.pkl')
print("Model trained and saved as model.pkl!")

Model trained and saved as model.pkl!